# Ultralytics Discord Bot Documentation Configuration File

DOCS_URL: https://docs.ultralytics.com/
GH_REPO: https://github.com/ultralytics/ultralytics.git
ULTRA_LICENSING: https://www.ultralytics.com/license
LICENSE: AGPL-3.0

DOCS_DIR: docs
DOCS_LOC: en # english locale
DOCS_IDX: mkdocs # mkdocs.yml
YAML_EXT: ['.yaml', '.yml']

BRAND: 
  hub: HUB
  yolo: YOLO
  ultralytics: Ultralytics

LOGO_ICON: "https://raw.githubusercontent.com/ultralytics/assets/main/logo/Ultralytics-logomark-color.png"
INTGR8_BANNER: "https://raw.githubusercontent.com/ultralytics/assets/main/yolov8/banner-integrations.png"
BGRD_LOGO: "https://raw.githubusercontent.com/ultralytics/assets/main/im/banner-ultralytics-github.png"
# FULL_LOGO = "https://raw.githubusercontent.com/ultralytics/assets/main/logo/Ultralytics-logotype-color.png"
FULL_LOGO: "https://github.com/Burhan-Q/Ultralytics_DiscordBot/assets/62214284/ec6ef857-72b1-407b-b078-b2c3e8e34df0"
YOLO_LOGO: "https://raw.githubusercontent.com/ultralytics/assets/main/logo/discord/emote-Ultralytics_YOLO_Logomark.png"

CATEGORIES: 
  - Modes
  - Tasks
  - Models
  - Datasets
  - Guides
  - YOLOv5
  - HUB
  - Integrations
  - Help
  - Usage
  - Quickstart
  - Real-World Projects
  - Tutorials
  #- 'NEW 🚀 Explorer'

IGNORE:
  - Reference

ALL_CAPS: 
  - YOLO
  - CLI
  - JSON
  - YAML
  - HUB
  - API
  - URL
  - OBB
  - TCP
  - RTSP
  - ONNX
  - TF.JS
  - TF
  - NCNN
  - CNN
  - COCO