services:
  bot:
    container_name: ubot
    build: 
      context: .
      args:
        REPO_DIR: repo_data
    volumes:
      - type: bind
        source: ./
        target: /bot # logs saving to /bot/bot.log 
      # untested, possible volume may not work

# start with docker compose up -d --build