import yaml

from UltralyticsBot import PROJ_ROOT

DOCS_CFG = yaml.safe_load((PROJ_ROOT / "cfg/docs_config.yaml").read_text("utf-8"))

DOCS_URL = DOCS_CFG.get("DOCS_URL")
GH_REPO = DOCS_CFG.get("GH_REPO")
ULTRA_LICENSING = DOCS_CFG.get("ULTRA_LICENSING")
LICENSE = DOCS_CFG.get("LICENSE")
DOCS_DIR = DOCS_CFG.get("DOCS_DIR")
DOCS_LOC = DOCS_CFG.get("DOCS_LOC")
DOCS_IDX = DOCS_CFG.get("DOCS_IDX")
YAML_EXT = DOCS_CFG.get("YAML_EXT")
BRAND = DOCS_CFG.get("BRAND")
LOGO_ICON = DOCS_CFG.get("LOGO_ICON")
INTGR8_BANNER = DOCS_CFG.get("INTGR8_BANNER")
BGRD_LOGO = DOCS_CFG.get("BGRD_LOGO")
FULL_LOGO = DOCS_CFG.get("FULL_LOGO")
YOLO_LOGO = DOCS_CFG.get("YOLO_LOGO")
CATEGORIES = DOCS_CFG.get("CATEGORIES")
ALL_CAPS = DOCS_CFG.get("ALL_CAPS")
IGNORE = DOCS_CFG.get("IGNORE")


__all__ = "DOCS_CFG", "DOCS_URL", "GH_REPO", "ULTRA_LICENSING", "LICENSE", "DOCS_DIR", "DOCS_LOC", "DOCS_IDX", "YAML_EXT", "BRAND", "LOGO_ICON", "INTGR8_BANNER", "BGRD_LOGO", "FULL_LOGO", "YOLO_LOGO", "CATEGORIES", "ALL_CAPS", "IGNORE"

